### ISSUE TITLE
Propuesta

### ISSUE THREAD

**Issue by Onioninblack** [WallaceMcGregor/trophy-dark-srd#1]
Muy chula la ficha!
Queria sugerir que en lugar de escribir el número de dados a tirar haya una barra como en ruina.
Eso permitiria poner los dados que se tiran de forma mucho más ágil.

La formula también se podría modificar para que enseñara directamente el dado más alto.  Hace un año que no toco foundry y no soy capaz de decir como pero se puede. 

Muy buen trabajo de todas formas, esto es sólo una recomendación de mejora.

**Comment by WallaceMcGregor** [comment]
Muchas gracias por los comentarios, Pau.

Se lo he comentado a Regik, que ha sido realmente el autor de la ficha (yo hace mucho que no toco Sandbox y no me atrevería a tocarla 😅). En cualquier caso, lo de la barra con los dados a tirar, es más complicado, dado que hay situaciones en las que puedes llegar a tirar "todos los dados que quieras".

Gracias.

**Comment by WallaceMcGregor** [comment]
Solucionado parcialmente en la versión [1.1.0](https://github.com/WallaceMcGregor/trophy-dark-srd/releases/tag/1.1.0).

- Se modifica la fórmula de la tirada para que se muestre de manera descriptiva en el chat.
- Como consecuencia, la tirada no es compatible con la configuración de dados de **Dice So Nice**.

Se subirá próximamente al repositorio de Foundry (cuando no me dé error al acceder).

**Comment by WallaceMcGregor** [comment]
Modificado nuevamente en la versión [1.2.0](https://github.com/WallaceMcGregor/trophy-dark-srd/releases/tag/1.2.0) para implementar el uso con **Dice So Nice**.
