### ISSUE TITLE
Bug con algunos resultados en las descripciones de las tiradas.

### ISSUE THREAD

**Issue by dmr612** [WallaceMcGregor/trophy-dark-srd#2]
Pues eso, algunos lanzamientos parecen mostrar una descripción errónea en la línea de texto "Éxito completo ----"  aunque se cumpla la condición 0:oscuro,1:claro. Además de ello algunos lanzamientos no aparecen y muchos otros tardan mucho en aparecer, sobre todo en el chat. De resto, muy sólido el sistema.

**Comment by WallaceMcGregor** [comment]
Yo lo estuve probando la semana pasada (y hoy volveré a jugar) y funciona bien. Lo único que cuando hay empate de resultado entre oscuro y claro, no lo determina como oscuro (según las reglas), pero eso son limitaciones de Sandbox.

También tengo que decirte que yo lo estoy utilizando en la versión de Foundry 0.8.9, no en la 0.9.X ni con las últimas versiones de Sandbox. Pero Regik, que fue el que hizo el núcleo del sistema, lo hizo en la 9.

Así que no sé si es por que estás en las últimas versiones de Sandbox y ha añadido algo que rompe el sistema. No sé realmente cuál puede ser el problema ahora mismo, la verdad.

**Comment by dmr612** [comment]
![image](https://user-images.githubusercontent.com/53447795/174613585-69b4230b-5eb5-4052-8ecf-364b61358511.png) 
![image](https://user-images.githubusercontent.com/53447795/174613650-6ac7f235-7c60-4d70-b31d-1d9f8d710537.png)
Va algo asi

**Comment by WallaceMcGregor** [comment]
Acabo de comprobar que solo pasa cuando tiras 2 y 2 dados. En cualquier otra combinación, al menos a mi, me va bien. Ya no sé qué pasará con Sandbox para que funcione así solo en esa situación.

**Comment by WallaceMcGregor** [comment]
Vale, creo que lo he podido solucionar gracias a la ayuda que he recibido en el Discord de Rol NL. Pruébalo y ya me dices.

**Comment by dmr612** [comment]
Funcionando perfectamente! Gracias!
